name: next_dimension
version: 0.0.1 
description: A pub package 
dependencies:
  browser: any  ## '>=0.9.0 <0.10.0'
  vector_math: any ## '>=1.3.5 <1.4.0'
  
  ##three: any
  
  three:
    ##git: https://github.com/threeDart/three.dart.git
    path: ../three_dart_fork_simplify
  stats:
    git: https://github.com/financeCoding/stats.dart.git
    
    

